
instrumentation:
    excludes: ['*-spec.js', 'spec/*']
reporting:
    dir: ./docs/coverage/
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
